Python: Black Friday Analysis

Data Analysis using Pandas

Pandas is an open source library for data analysis in python. It is one of those packages that makes analysing data much easier. It helps to manage data and it used two data types for storing data:
1. Series
2. DataFrame

Data Frame like an excel spreadsheet that is storing data. A dataframe is made up of several series. Each column of a dataframe is a series.

Series: It is one dimensional , labeled and homogenous array.
DataFrames: It is two dimensional tabular data structure.

Some key features of Pandas:

Data Manipulation:
Pandas provides tools for:
Data cleaning: Handling missing values (NaN), removing duplicates, and cleaning messy data.
Data filtering and selection: Extracting specific data based on labels or conditions.
Data aggregation: Grouping and summarizing data using functions like sum, mean, or count.
Data transformation: Reshaping, pivoting, and merging data sets.

Data Input/Output:
It supports reading and writing data from various file formats, such as CSV, Excel, SQL databases, and more.

Data Analysis:
Pandas enables:
Descriptive statistics: Calculating measures like mean, median, standard deviation, etc.
Correlation analysis: Identifying relationships between variables.
Time series analysis: Handling and analyzing time-indexed data.

Integration:
It seamlessly integrates with other Python libraries like NumPy, Matplotlib, and scikit-learn, enhancing data analysis workflows.

Efficiency:
Pandas is built for performance, leveraging optimized C or Cython code for speed, especially when working with large datasets.
Flexibility:
It offers a wide range of options and customizations for data manipulation and analysis, adapting to diverse needs.

Mutability:
Columns can be added or removed from DataFrames.
Visualization:
Pandas integrates with libraries like Matplotlib and Seaborn, making it easy to visualize data.

Lets Proceed with Handson with python:

Black Friday Dataset:
This dataset comprises of sales transection captured at a retail store. It is classic dataset to explore and expand your feature engineering skills and day to day understanding from multiple shopping experiences. The dataset has 550,069 rows and 12 cloumns.

Problem: Predict Purchase Amount

Data:


Variable             Definition
User_ID              User ID
Product_ID           Product ID
Gender               Sex of user
Age                  Age in bins
Occupation           Occupation (Masked)
City_Category        Category of the city(A,B,C)
Stay_in_current_city_years   Number of years stay in current city
Marital_Status       Merital Status
Product_Category_1   Product Category (Masked)
Product_Category_2   Product may belong to other category also (Masked)
Product_Category_3   Product may belong to other category also (Masked)
Purchase             Purchase Amount (Target Variable)

Importing Pandas

Task 1: Import Pandas


In [2]:
import pandas 

usually we import pandas library by appending the alias as pd. It makes things easier because now instead of writing pandas.command we need to write pd.command

In [3]:
#Import using alias
import pandas as pd

After importing we can go ahead with data loading but weight first lets set some values i.e Maximum number of rows and columns can be seen. We have default value either we can use same or we can change if we are handling some large dataseta and we want to get some customized number of rows and columns.

Task 2: Change default values for displaying rows and columns

In [4]:
#display default maximum rows
pd.get_option('display.max_rows')

60

In [5]:
#display default maximum coloumns 
pd.get_option('display.max_columns')

20

In [6]:
#lets set max rows
pd.set_option('display.max_rows', 80)  #this is just for understanding, but actual our dataset has 550,069 rows and 12 cloumns.

In [7]:
#lets set max columns
pd.set_option('display.max_columns', 40)  #this is just for understanding, but actual our dataset has 550,069 rows and 12 cloumns.

In [8]:
#Reset to default values

#If you still want to use some default values
#pd.reset_option('display.max_rows')
#pd.reset_option('display.max_columns')

Reading Dataset

Task 3:  Read Dataset Using Pandas

We can load/download data with different file format in pandas using below functions

CSV:
read_csv(): Reads data from a CSV file into a DataFrame.
to_csv(): Writes a DataFrame to a CSV file.
Excel:
read_excel(): Reads data from an Excel file into a DataFrame.
to_excel(): Writes a DataFrame to an Excel file.
JSON:
read_json(): Reads data from a JSON file into a DataFrame.
to_json(): Writes a DataFrame to a JSON file.
SQL:
read_sql(): Reads data from a SQL database into a DataFrame.
to_sql(): Writes a DataFrame to a SQL database.
Parquet:
read_parquet(): Reads data from a Parquet file into a DataFrame.
to_parquet(): Writes a DataFrame to a Parquet file.
Other formats:
read_table(): Reads data from a delimited text file (can be used for various formats by specifying the delimiter).
read_fwf(): Reads data from a fixed-width formatted file.
read_html(): Reads HTML tables into a DataFrame.
read_clipboard(): Reads data from the clipboard.
These functions offer various parameters to customize the reading and writing process, such as specifying delimiters, headers, data types, and more. They enable seamless integration of pandas with diverse data sources and formats.

In [10]:
#As we have data in csv format so lets use read_csv for loading dataset

df = pd.read_csv('blackfriday.csv')

In [11]:
#lets check type of df
type(df)

pandas.core.frame.DataFrame

Task 4: Find shape of dataframe i.e number of rows and columns 

In [12]:
#lets check the shape of dataframe
df.shape

(550068, 12)

The dataset has 550,069 rows and 12 cloumns

In [13]:
#check dimension of dataframe (ndim= n dimensional)
df.ndim

2

Exploring the dataset

Task 5: Print top 10 rows and last 10 rows of the dataframe using head()
df.head()

In [14]:
df.head()

User_ID Product_ID Gender   Age  Occupation City_Category  \
0  1000001  P00069042      F  0-17          10             A   
1  1000001  P00248942      F  0-17          10             A   
2  1000001  P00087842      F  0-17          10             A   
3  1000001  P00085442      F  0-17          10             A   
4  1000002  P00285442      M   55+          16             C   

  Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
0                          2               0                   3   
1                          2               0                   1   
2                          2               0                  12   
3                          2               0                  12   
4                         4+               0                   8   

   Product_Category_2  Product_Category_3  Purchase  
0                 NaN                 NaN      8370  
1                 6.0                14.0     15200  
2                 NaN                 NaN      1422  
3                14.0                 NaN      1057  
4                 NaN                 NaN      7969

In [15]:
#lets customize and check for top 10 rows 

df.head(10)

User_ID Product_ID Gender    Age  Occupation City_Category  \
0  1000001  P00069042      F   0-17          10             A   
1  1000001  P00248942      F   0-17          10             A   
2  1000001  P00087842      F   0-17          10             A   
3  1000001  P00085442      F   0-17          10             A   
4  1000002  P00285442      M    55+          16             C   
5  1000003  P00193542      M  26-35          15             A   
6  1000004  P00184942      M  46-50           7             B   
7  1000004  P00346142      M  46-50           7             B   
8  1000004   P0097242      M  46-50           7             B   
9  1000005  P00274942      M  26-35          20             A   

  Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
0                          2               0                   3   
1                          2               0                   1   
2                          2               0                  12   
3                          2               0                  12   
4                         4+               0                   8   
5                          3               0                   1   
6                          2               1                   1   
7                          2               1                   1   
8                          2               1                   1   
9                          1               1                   8   

   Product_Category_2  Product_Category_3  Purchase  
0                 NaN                 NaN      8370  
1                 6.0                14.0     15200  
2                 NaN                 NaN      1422  
3                14.0                 NaN      1057  
4                 NaN                 NaN      7969  
5                 2.0                 NaN     15227  
6                 8.0                17.0     19215  
7                15.0                 NaN     15854  
8                16.0                 NaN     15686  
9                 NaN                 NaN      7871

In [16]:
#we can also check rows from the last using tail(). by default, it also give last 5. lets check for last 10 rows 
df.tail(10)

User_ID Product_ID Gender    Age  Occupation City_Category  \
550058  1006024  P00372445      M  26-35          12             A   
550059  1006025  P00370853      F  26-35           1             B   
550060  1006026  P00371644      M  36-45           6             C   
550061  1006029  P00372445      F  26-35           1             C   
550062  1006032  P00372445      M  46-50           7             A   
550063  1006033  P00372445      M  51-55          13             B   
550064  1006035  P00375436      F  26-35           1             C   
550065  1006036  P00375436      F  26-35          15             B   
550066  1006038  P00375436      F    55+           1             C   
550067  1006039  P00371644      F  46-50           0             B   

       Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
550058                          0               1                  20   
550059                          1               0                  19   
550060                          1               1                  20   
550061                          1               1                  20   
550062                          3               0                  20   
550063                          1               1                  20   
550064                          3               0                  20   
550065                         4+               1                  20   
550066                          2               0                  20   
550067                         4+               1                  20   

        Product_Category_2  Product_Category_3  Purchase  
550058                 NaN                 NaN       121  
550059                 NaN                 NaN        48  
550060                 NaN                 NaN       494  
550061                 NaN                 NaN       599  
550062                 NaN                 NaN       473  
550063                 NaN                 NaN       368  
550064                 NaN                 NaN       371  
550065                 NaN                 NaN       137  
550066                 NaN                 NaN       365  
550067                 NaN                 NaN       490

In [17]:
#checking for duplicate rows
df.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...  
550063    False
550064    False
550065    False
550066    False
550067    False
Length: 550068, dtype: bool

In [18]:
#sum of total rows which are having duplicate data
sum(df.duplicated())

0

Task 7: Create new dataset with all product related column

In [19]:
#lets check column present in dataframe (the 'Product' Column)
df.columns

Index(['User_ID', 'Product_ID', 'Gender', 'Age', 'Occupation', 'City_Category',
       'Stay_In_Current_City_Years', 'Marital_Status', 'Product_Category_1',
       'Product_Category_2', 'Product_Category_3', 'Purchase'],
      dtype='object')

Lets try to create another dataset which will be subset of original and will have columns related to product

In [20]:
#first of all lets check for all columns which is having details related to 'Product'
[i for i in df.columns if 'Product' in i]

['Product_ID',
 'Product_Category_1',
 'Product_Category_2',
 'Product_Category_3']

In [21]:
#lets create new dataframe with these product related column
df_product= df[['Product_ID','Product_Category_1', 'Product_Category_2', 'Product_Category_3']]   #doble bracket will give you subset of these column

In [22]:
#print dataframe from new dataframe
df_product

Product_ID  Product_Category_1  Product_Category_2  Product_Category_3
0       P00069042                   3                 NaN                 NaN
1       P00248942                   1                 6.0                14.0
2       P00087842                  12                 NaN                 NaN
3       P00085442                  12                14.0                 NaN
4       P00285442                   8                 NaN                 NaN
...           ...                 ...                 ...                 ...
550063  P00372445                  20                 NaN                 NaN
550064  P00375436                  20                 NaN                 NaN
550065  P00375436                  20                 NaN                 NaN
550066  P00375436                  20                 NaN                 NaN
550067  P00371644                  20                 NaN                 NaN

[550068 rows x 4 columns]

In [23]:
#axes returns a list of the row axes labels as well as columns 
df.axes

[RangeIndex(start=0, stop=550068, step=1),
 Index(['User_ID', 'Product_ID', 'Gender', 'Age', 'Occupation', 'City_Category',
        'Stay_In_Current_City_Years', 'Marital_Status', 'Product_Category_1',
        'Product_Category_2', 'Product_Category_3', 'Purchase'],
       dtype='object')]

In [24]:
#in perticular you want access some values (values returns the series of values as ndarray)
df.Gender.values

array(['F', 'F', 'F', ..., 'F', 'F', 'F'], dtype=object)

In [25]:
#size return the number of elements in the underlying dataset/column. lets try with dataset first
df.size   #size= column*row

6600816

In [26]:
#lets to check  size of gender column
df.Gender.size

550068

View concise summary of dataframe

Task 8: check for all column datatype and related counts

We can view the concise summary of dataframe with info() method 

In [27]:
#lets use info() function
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550068 entries, 0 to 550067
Data columns (total 12 columns):
 #   Column                      Non-Null Count   Dtype  
---  ------                      --------------   -----  
 0   User_ID                     550068 non-null  int64  
 1   Product_ID                  550068 non-null  object 
 2   Gender                      550068 non-null  object 
 3   Age                         550068 non-null  object 
 4   Occupation                  550068 non-null  int64  
 5   City_Category               550068 non-null  object 
 6   Stay_In_Current_City_Years  550068 non-null  object 
 7   Marital_Status              550068 non-null  int64  
 8   Product_Category_1          550068 non-null  int64  
 9   Product_Category_2          376430 non-null  float64
 10  Product_Category_3          166821 non-null  float64
 11  Purchase                    550068 non-null  int64  
dtypes: float64(2), int64(5), object(5)
memory usage: 50.4+ MB


int64, float64 and object of the datatypes of our features

With this same method, we can easily if there are any missing values. Here there are some missing values becz each column should contain 550068 observations, the same number of rows we saw before with shape. But for some column there is less count.

In [28]:
#lets only check datatype of each column
df.dtypes


User_ID                         int64
Product_ID                     object
Gender                         object
Age                            object
Occupation                      int64
City_Category                  object
Stay_In_Current_City_Years     object
Marital_Status                  int64
Product_Category_1              int64
Product_Category_2            float64
Product_Category_3            float64
Purchase                        int64
dtype: object

Task : Change data type of 'Purchase' to float.

We can also change the column type with the astype method

In [29]:
#lets try to change 'Purchase to float datatypes
df['Purchase']= df['Purchase'].astype('float64')

In [30]:
#lets verify
df.dtypes

User_ID                         int64
Product_ID                     object
Gender                         object
Age                            object
Occupation                      int64
City_Category                  object
Stay_In_Current_City_Years     object
Marital_Status                  int64
Product_Category_1              int64
Product_Category_2            float64
Product_Category_3            float64
Purchase                      float64
dtype: object

In [31]:
df.head()

User_ID Product_ID Gender   Age  Occupation City_Category  \
0  1000001  P00069042      F  0-17          10             A   
1  1000001  P00248942      F  0-17          10             A   
2  1000001  P00087842      F  0-17          10             A   
3  1000001  P00085442      F  0-17          10             A   
4  1000002  P00285442      M   55+          16             C   

  Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
0                          2               0                   3   
1                          2               0                   1   
2                          2               0                  12   
3                          2               0                  12   
4                         4+               0                   8   

   Product_Category_2  Product_Category_3  Purchase  
0                 NaN                 NaN    8370.0  
1                 6.0                14.0   15200.0  
2                 NaN                 NaN    1422.0  
3                14.0                 NaN    1057.0  
4                 NaN                 NaN    7969.0

In [32]:
#change 'Purchase' back to int
df['Purchase']= df['Purchase'].astype('int64')

In [33]:
df.head()

User_ID Product_ID Gender   Age  Occupation City_Category  \
0  1000001  P00069042      F  0-17          10             A   
1  1000001  P00248942      F  0-17          10             A   
2  1000001  P00087842      F  0-17          10             A   
3  1000001  P00085442      F  0-17          10             A   
4  1000002  P00285442      M   55+          16             C   

  Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
0                          2               0                   3   
1                          2               0                   1   
2                          2               0                  12   
3                          2               0                  12   
4                         4+               0                   8   

   Product_Category_2  Product_Category_3  Purchase  
0                 NaN                 NaN      8370  
1                 6.0                14.0     15200  
2                 NaN                 NaN      1422  
3                14.0                 NaN      1057  
4                 NaN                 NaN      7969

Task 9: Generate descriptive statistical values for numerical columns.

The describe method shows basic statistical characteristics of each numerical featureb(int64 and float64) type: the number of non missing values, mean, std deviation, range , median, 0.25 and 0.75 quartiles

In [34]:
#lets use describe on top of dataset
df.describe()

#max helps in getting the outlier values present in dataset

User_ID     Occupation  Marital_Status  Product_Category_1  \
count  5.500680e+05  550068.000000   550068.000000       550068.000000   
mean   1.003029e+06       8.076707        0.409653            5.404270   
std    1.727592e+03       6.522660        0.491770            3.936211   
min    1.000001e+06       0.000000        0.000000            1.000000   
25%    1.001516e+06       2.000000        0.000000            1.000000   
50%    1.003077e+06       7.000000        0.000000            5.000000   
75%    1.004478e+06      14.000000        1.000000            8.000000   
max    1.006040e+06      20.000000        1.000000           20.000000   

       Product_Category_2  Product_Category_3       Purchase  
count       376430.000000       166821.000000  550068.000000  
mean             9.842329           12.668243    9263.968713  
std              5.086590            4.125338    5023.065394  
min              2.000000            3.000000      12.000000  
25%              5.000000            9.000000    5823.000000  
50%              9.000000           14.000000    8047.000000  
75%             15.000000           16.000000   12054.000000  
max             18.000000           18.000000   23961.000000

Task 10: Try to use some function in categorical column

We can also use describe for other data types using include options

In [35]:
#Apart from int and float, we  have datatype as object. lets do for those column

df.describe(include=['object'])

Product_ID  Gender     Age City_Category Stay_In_Current_City_Years
count      550068  550068  550068        550068                     550068
unique       3631       2       7             3                          5
top     P00265242       M   26-35             B                          1
freq         1880  414259  219587        231173                     193821

Task 11: Get percentage distribution of each product id available in dataset and find with highest occuring product id in dataset

We can use value_counts for checking different values in categorical columns

In [36]:
#lets check for product_id
#if you want product_id value count

df['Product_ID'].value_counts()

Product_ID
P00265242    1880
P00025442    1615
P00110742    1612
P00112142    1562
P00057642    1470
             ... 
P00314842       1
P00298842       1
P00231642       1
P00204442       1
P00066342       1
Name: count, Length: 3631, dtype: int64

In [37]:
#Get normalize value

df['Product_ID'].value_counts(normalize= True)

Product_ID
P00265242    0.003418
P00025442    0.002936
P00110742    0.002931
P00112142    0.002840
P00057642    0.002672
               ...   
P00314842    0.000002
P00298842    0.000002
P00231642    0.000002
P00204442    0.000002
P00066342    0.000002
Name: proportion, Length: 3631, dtype: float64

In [38]:
#multiply it with 100 to get percentage value and round it up to 3 decimal place

round(df['Product_ID'].value_counts(normalize= True)*100,3)

Product_ID
P00265242    0.342
P00025442    0.294
P00110742    0.293
P00112142    0.284
P00057642    0.267
             ...  
P00314842    0.000
P00298842    0.000
P00231642    0.000
P00204442    0.000
P00066342    0.000
Name: proportion, Length: 3631, dtype: float64

In [39]:
#check sum of all percentage values
round(df['Product_ID'].value_counts(normalize= True)*100,3).sum()

99.97600000000001

In [40]:
(df['Product_ID'].value_counts(normalize= True)*100).sum()

100.0

# we can see product id P00265242 with highest percentage as compare to others hence this product has been purchased more.

Handling Missing Values

Task 12: Check for columns having null values and count of null containing rows 
 Pandas provides isna() and notna() functions to detect 'NA' Values.
 detect 'NA' values in the dataframe: df.isna().sum()
 detect 'NA' values in perticular column in the dataframe: pd.isna(df['col_name'].notna()
 isnull() is just an alias of the isna() method in pandas source code.

In [42]:
#lets check on our dataset
df.isnull()  #gives either dataset has conitain null row or not, if not not, gives false

User_ID  Product_ID  Gender    Age  Occupation  City_Category  \
0         False       False   False  False       False          False   
1         False       False   False  False       False          False   
2         False       False   False  False       False          False   
3         False       False   False  False       False          False   
4         False       False   False  False       False          False   
...         ...         ...     ...    ...         ...            ...   
550063    False       False   False  False       False          False   
550064    False       False   False  False       False          False   
550065    False       False   False  False       False          False   
550066    False       False   False  False       False          False   
550067    False       False   False  False       False          False   

        Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
0                            False           False               False   
1                            False           False               False   
2                            False           False               False   
3                            False           False               False   
4                            False           False               False   
...                            ...             ...                 ...   
550063                       False           False               False   
550064                       False           False               False   
550065                       False           False               False   
550066                       False           False               False   
550067                       False           False               False   

        Product_Category_2  Product_Category_3  Purchase  
0                     True                True     False  
1                    False               False     False  
2                     True                True     False  
3                    False                True     False  
4                     True                True     False  
...                    ...                 ...       ...  
550063                True                True     False  
550064                True                True     False  
550065                True                True     False  
550066                True                True     False  
550067                True                True     False  

[550068 rows x 12 columns]

In [43]:
df.isnull().sum()

# the null value in Product_Category_2  is 173638
#Product_Category_3 is  383247

User_ID                            0
Product_ID                         0
Gender                             0
Age                                0
Occupation                         0
City_Category                      0
Stay_In_Current_City_Years         0
Marital_Status                     0
Product_Category_1                 0
Product_Category_2            173638
Product_Category_3            383247
Purchase                           0
dtype: int64

In [44]:
#print Product_Category_2

df.Product_Category_2    #it has null values

0          NaN
1          6.0
2          NaN
3         14.0
4          NaN
          ... 
550063     NaN
550064     NaN
550065     NaN
550066     NaN
550067     NaN
Name: Product_Category_2, Length: 550068, dtype: float64

In [45]:
df.Product_Category_3  #it has null values

0          NaN
1         14.0
2          NaN
3          NaN
4          NaN
          ... 
550063     NaN
550064     NaN
550065     NaN
550066     NaN
550067     NaN
Name: Product_Category_3, Length: 550068, dtype: float64

Sometimes missing values are encoded in different ways . They can appear as NaN, NA, ?, zeros , xx, -1 or a blank space ""

But pandas always recognize missing values as NaN. So it is essential that we should first convert all the ?, zeros , xx, -1 or "" to NaN, If the missing value isn't identified as NaN then we have to first convert or replace such non NaN entry with a NaN

Convert ? to NaN

df[df=='?']= np.nan

Task 13: Handling missing value using dropping and imputing both options

Handling missing values is a crucial step in data preprocessing. Two common approaches are dropping rows/columns with missing values and imputing the missing values. Both methods have their advantages and disadvantages, and the choice depends on the specific dataset and analysis goals.
Dropping Missing Values
Dropping involves removing rows or columns that contain missing values.

Imputing Missing Values (mean/median/mode/bfill/ffill)
Imputation involves filling in missing values with estimated values. Common imputation methods include mean, median, or mode imputation.

Considerations
Dropping:
Suitable when missing values are few and randomly distributed. However, it can lead to significant data loss if missing values are abundant.
Imputing:
Preserves data but can introduce bias if the imputed values are not representative of the true values. The choice of imputation method depends on the data distribution and the nature of missingness.
Advanced Imputation:
More sophisticated methods like k-NN imputation or model-based imputation can be used for better accuracy, but they are computationally more expensive.

In [46]:
#lets  first try with drop option. Dropping  Product_Category_2 using  axis 1
df_temp= df.drop('Product_Category_2', axis=1, inplace= False)

In [47]:
#lets verify with info()

df_temp.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550068 entries, 0 to 550067
Data columns (total 11 columns):
 #   Column                      Non-Null Count   Dtype  
---  ------                      --------------   -----  
 0   User_ID                     550068 non-null  int64  
 1   Product_ID                  550068 non-null  object 
 2   Gender                      550068 non-null  object 
 3   Age                         550068 non-null  object 
 4   Occupation                  550068 non-null  int64  
 5   City_Category               550068 non-null  object 
 6   Stay_In_Current_City_Years  550068 non-null  object 
 7   Marital_Status              550068 non-null  int64  
 8   Product_Category_1          550068 non-null  int64  
 9   Product_Category_3          166821 non-null  float64
 10  Purchase                    550068 non-null  int64  
dtypes: float64(1), int64(5), object(5)
memory usage: 46.2+ MB


In [48]:
#lets verify with isnull() functions
df_temp.isnull().sum()

User_ID                            0
Product_ID                         0
Gender                             0
Age                                0
Occupation                         0
City_Category                      0
Stay_In_Current_City_Years         0
Marital_Status                     0
Product_Category_1                 0
Product_Category_3            383247
Purchase                           0
dtype: int64

In [49]:
#get index for all rows with product_category_3 missing 
df_temp.Product_Category_3.isnull()

0          True
1         False
2          True
3          True
4          True
          ...  
550063     True
550064     True
550065     True
550066     True
550067     True
Name: Product_Category_3, Length: 550068, dtype: bool

In [50]:
#get index for all rows with product_category_3 missing 
df_temp[df_temp.Product_Category_3.isnull()].index


Index([     0,      2,      3,      4,      5,      7,      8,      9,     10,
           11,
       ...
       550058, 550059, 550060, 550061, 550062, 550063, 550064, 550065, 550066,
       550067],
      dtype='int64', length=383247)

In [51]:
#Drop product_category_3 using axis = 0
df_temp.drop(df_temp[df_temp.Product_Category_3.isnull()].index, axis=0, inplace=False)

User_ID Product_ID Gender    Age  Occupation City_Category  \
1       1000001  P00248942      F   0-17          10             A   
6       1000004  P00184942      M  46-50           7             B   
13      1000005  P00145042      M  26-35          20             A   
14      1000006  P00231342      F  51-55           9             A   
16      1000006   P0096642      F  51-55           9             A   
...         ...        ...    ...    ...         ...           ...   
545902  1006039  P00064042      F  46-50           0             B   
545904  1006040  P00081142      M  26-35           6             B   
545907  1006040  P00277642      M  26-35           6             B   
545908  1006040  P00127642      M  26-35           6             B   
545914  1006040  P00217442      M  26-35           6             B   

       Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
1                               2               0                   1   
6                               2               1                   1   
13                              1               1                   1   
14                              1               0                   5   
16                              1               0                   2   
...                           ...             ...                 ...   
545902                         4+               1                   3   
545904                          2               0                   6   
545907                          2               0                   2   
545908                          2               0                   1   
545914                          2               0                   1   

        Product_Category_3  Purchase  
1                     14.0     15200  
6                     17.0     19215  
13                     5.0     15665  
14                    14.0      5378  
16                     4.0     13055  
...                    ...       ...  
545902                12.0      8047  
545904                14.0     16493  
545907                10.0      3425  
545908                15.0     15694  
545914                11.0     11640  

[166821 rows x 11 columns]

In [52]:
#verify using info()
df_temp.info()   #here missing row got dropped  

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550068 entries, 0 to 550067
Data columns (total 11 columns):
 #   Column                      Non-Null Count   Dtype  
---  ------                      --------------   -----  
 0   User_ID                     550068 non-null  int64  
 1   Product_ID                  550068 non-null  object 
 2   Gender                      550068 non-null  object 
 3   Age                         550068 non-null  object 
 4   Occupation                  550068 non-null  int64  
 5   City_Category               550068 non-null  object 
 6   Stay_In_Current_City_Years  550068 non-null  object 
 7   Marital_Status              550068 non-null  int64  
 8   Product_Category_1          550068 non-null  int64  
 9   Product_Category_3          166821 non-null  float64
 10  Purchase                    550068 non-null  int64  
dtypes: float64(1), int64(5), object(5)
memory usage: 46.2+ MB


In [53]:
df_temp.info() 

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550068 entries, 0 to 550067
Data columns (total 11 columns):
 #   Column                      Non-Null Count   Dtype  
---  ------                      --------------   -----  
 0   User_ID                     550068 non-null  int64  
 1   Product_ID                  550068 non-null  object 
 2   Gender                      550068 non-null  object 
 3   Age                         550068 non-null  object 
 4   Occupation                  550068 non-null  int64  
 5   City_Category               550068 non-null  object 
 6   Stay_In_Current_City_Years  550068 non-null  object 
 7   Marital_Status              550068 non-null  int64  
 8   Product_Category_1          550068 non-null  int64  
 9   Product_Category_3          166821 non-null  float64
 10  Purchase                    550068 non-null  int64  
dtypes: float64(1), int64(5), object(5)
memory usage: 46.2+ MB


Here we will fill the missing value with forward and backward fill 

The pad or fill option fill values forward, while bfill or backfill option fill value backward

In [54]:
#impute using forward filling

df= df.fillna(method= 'pad')

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_2008\999171579.py:3: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df= df.fillna(method= 'pad')


In [55]:
#verify using isnull()

df.isnull().sum()

#in Product_Category_2 & Product_Category_3  1 row is missing

User_ID                       0
Product_ID                    0
Gender                        0
Age                           0
Occupation                    0
City_Category                 0
Stay_In_Current_City_Years    0
Marital_Status                0
Product_Category_1            0
Product_Category_2            1
Product_Category_3            1
Purchase                      0
dtype: int64

In [56]:
#check
df.head()

User_ID Product_ID Gender   Age  Occupation City_Category  \
0  1000001  P00069042      F  0-17          10             A   
1  1000001  P00248942      F  0-17          10             A   
2  1000001  P00087842      F  0-17          10             A   
3  1000001  P00085442      F  0-17          10             A   
4  1000002  P00285442      M   55+          16             C   

  Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
0                          2               0                   3   
1                          2               0                   1   
2                          2               0                  12   
3                          2               0                  12   
4                         4+               0                   8   

   Product_Category_2  Product_Category_3  Purchase  
0                 NaN                 NaN      8370  
1                 6.0                14.0     15200  
2                 6.0                14.0      1422  
3                14.0                14.0      1057  
4                14.0                14.0      7969

So here we get that forward filling is not worth it to use becz there is not forward value before NaN in product_id P00069042 in both product_cat2 and product_cat3

In [57]:
#Print both columns

df[['Product_Category_2', 'Product_Category_3']].head()

Product_Category_2  Product_Category_3
0                 NaN                 NaN
1                 6.0                14.0
2                 6.0                14.0
3                14.0                14.0
4                14.0                14.0

In [58]:
#impute using backward filling
df = df.fillna(method='backfill')

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_2008\456906053.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df = df.fillna(method='backfill')


In [59]:
df.head()

User_ID Product_ID Gender   Age  Occupation City_Category  \
0  1000001  P00069042      F  0-17          10             A   
1  1000001  P00248942      F  0-17          10             A   
2  1000001  P00087842      F  0-17          10             A   
3  1000001  P00085442      F  0-17          10             A   
4  1000002  P00285442      M   55+          16             C   

  Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
0                          2               0                   3   
1                          2               0                   1   
2                          2               0                  12   
3                          2               0                  12   
4                         4+               0                   8   

   Product_Category_2  Product_Category_3  Purchase  
0                 6.0                14.0      8370  
1                 6.0                14.0     15200  
2                 6.0                14.0      1422  
3                14.0                14.0      1057  
4                14.0                14.0      7969

In [60]:
#verify using isnull()
df.isnull().sum()

User_ID                       0
Product_ID                    0
Gender                        0
Age                           0
Occupation                    0
City_Category                 0
Stay_In_Current_City_Years    0
Marital_Status                0
Product_Category_1            0
Product_Category_2            0
Product_Category_3            0
Purchase                      0
dtype: int64

Indexing and Slicing in Pandas

Task 14: Print age and occupation columns using loc and select 1st, 5th and 10th rows with 1st, 4th and 7th column using iloc

Here now we will see how to slice and dice the data and get the subset of pandas dataframe

.iloc - integer based
.loc - label based

To slice and dice Pandas DataFrames, use .iloc for integer-based indexing (position) and .loc for label-based indexing (labels) to select specific rows and columns. 
.iloc (Integer-based Indexing)
Purpose: Accesses data by numerical position (0-based indexing). 
How to use:
df.iloc[row_index] - Selects a specific row. 
df.iloc[start:end] - Selects a range of rows (end is exclusive). 
df.iloc[[row_index1, row_index2]] - Selects specific rows by a list of indices. 
df.iloc[:, col_index] - Selects a specific column. 
df.iloc[:, start:end] - Selects a range of columns. 
df.iloc[row_index, col_index] - Selects a specific cell. 
Example: df.iloc[0] returns the first row, df.iloc[1:3] returns rows 1 and 2 (excluding 3), and df.iloc[:, 0] returns the first column. 
Note: .iloc uses integer positions, not labels. 
.loc (Label-based Indexing)
Purpose: Accesses data by labels (row and column names). 
How to use:
df.loc[row_label] - Selects a specific row by its label. 
df.loc[start_label:end_label] - Selects a range of rows (including both start and end labels). 
df.loc[[row_label1, row_label2]] - Selects specific rows by a list of labels. 
df.loc[:, col_label] - Selects a specific column by its label. 
df.loc[:, start_col_label:end_col_label] - Selects a range of columns. 
df.loc[row_label, col_label] - Selects a specific cell. 
Example: df.loc['A'] returns the row labeled 'A', df.loc['A':'C'] returns rows 'A', 'B', and 'C', and df.loc[:, 'Column1'] returns the column labeled 'Column1'. 
Note: .loc uses labels, not integer positions

In [61]:
df.head()

User_ID Product_ID Gender   Age  Occupation City_Category  \
0  1000001  P00069042      F  0-17          10             A   
1  1000001  P00248942      F  0-17          10             A   
2  1000001  P00087842      F  0-17          10             A   
3  1000001  P00085442      F  0-17          10             A   
4  1000002  P00285442      M   55+          16             C   

  Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
0                          2               0                   3   
1                          2               0                   1   
2                          2               0                  12   
3                          2               0                  12   
4                         4+               0                   8   

   Product_Category_2  Product_Category_3  Purchase  
0                 6.0                14.0      8370  
1                 6.0                14.0     15200  
2                 6.0                14.0      1422  
3                14.0                14.0      1057  
4                14.0                14.0      7969

In [62]:
#make a copy of dataframe

df1= df.copy()

In [63]:
#print dataframe

df1

User_ID Product_ID Gender    Age  Occupation City_Category  \
0       1000001  P00069042      F   0-17          10             A   
1       1000001  P00248942      F   0-17          10             A   
2       1000001  P00087842      F   0-17          10             A   
3       1000001  P00085442      F   0-17          10             A   
4       1000002  P00285442      M    55+          16             C   
...         ...        ...    ...    ...         ...           ...   
550063  1006033  P00372445      M  51-55          13             B   
550064  1006035  P00375436      F  26-35           1             C   
550065  1006036  P00375436      F  26-35          15             B   
550066  1006038  P00375436      F    55+           1             C   
550067  1006039  P00371644      F  46-50           0             B   

       Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
0                               2               0                   3   
1                               2               0                   1   
2                               2               0                  12   
3                               2               0                  12   
4                              4+               0                   8   
...                           ...             ...                 ...   
550063                          1               1                  20   
550064                          3               0                  20   
550065                         4+               1                  20   
550066                          2               0                  20   
550067                         4+               1                  20   

        Product_Category_2  Product_Category_3  Purchase  
0                      6.0                14.0      8370  
1                      6.0                14.0     15200  
2                      6.0                14.0      1422  
3                     14.0                14.0      1057  
4                     14.0                14.0      7969  
...                    ...                 ...       ...  
550063                 2.0                11.0       368  
550064                 2.0                11.0       371  
550065                 2.0                11.0       137  
550066                 2.0                11.0       365  
550067                 2.0                11.0       490  

[550068 rows x 12 columns]

In [64]:
#select first row of dataframe using loc
df1.loc[0]

User_ID                         1000001
Product_ID                    P00069042
Gender                                F
Age                                0-17
Occupation                           10
City_Category                         A
Stay_In_Current_City_Years            2
Marital_Status                        0
Product_Category_1                    3
Product_Category_2                  6.0
Product_Category_3                 14.0
Purchase                           8370
Name: 0, dtype: object

In [65]:
#lets try to print 'Purchase' for all rows loc

df1.loc[0, 'Product_ID']

'P00069042'

In [66]:
#lets try to print "Purchase" for all rows using loc
df1.loc[:, 'Purchase']  #for all row use :

0          8370
1         15200
2          1422
3          1057
4          7969
          ...  
550063      368
550064      371
550065      137
550066      365
550067      490
Name: Purchase, Length: 550068, dtype: int64

In [67]:
#select first five rows for a specific column 'Purchase'

df1.loc[:4, 'Purchase']

0     8370
1    15200
2     1422
3     1057
4     7969
Name: Purchase, dtype: int64

In [68]:
#using head() also can get first five rows

df1.loc[:, 'Purchase'].head()

0     8370
1    15200
2     1422
3     1057
4     7969
Name: Purchase, dtype: int64

In [69]:
#print 'Age' and 'Occupation' using loc

df1.loc[:, ['Purchase','Age']]

Purchase    Age
0           8370   0-17
1          15200   0-17
2           1422   0-17
3           1057   0-17
4           7969    55+
...          ...    ...
550063       368  51-55
550064       371  26-35
550065       137  26-35
550066       365    55+
550067       490  46-50

[550068 rows x 2 columns]

In [70]:
#we can also specify row label. lets print first five rows with age and occupation columns
df1.loc[[0, 1, 2, 3, 4], ['Age', 'Occupation']]

Age  Occupation
0  0-17          10
1  0-17          10
2  0-17          10
3  0-17          10
4   55+          16

In [71]:
#same result we can verify using head()
df1.loc[:,['Age', 'Occupation']].head()

Age  Occupation
0  0-17          10
1  0-17          10
2  0-17          10
3  0-17          10
4   55+          16

In [72]:
#lets try to print all columns for 2nd, 3rd and 4th row 

df1.loc[2:4]

User_ID Product_ID Gender   Age  Occupation City_Category  \
2  1000001  P00087842      F  0-17          10             A   
3  1000001  P00085442      F  0-17          10             A   
4  1000002  P00285442      M   55+          16             C   

  Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
2                          2               0                  12   
3                          2               0                  12   
4                         4+               0                   8   

   Product_Category_2  Product_Category_3  Purchase  
2                 6.0                14.0      1422  
3                14.0                14.0      1057  
4                14.0                14.0      7969

Integer position based indexing using .iloc indexer

.iloc (Integer-based Indexing)
Purpose: Accesses data by numerical position (0-based indexing). 


.loc (Label-based Indexing)
Purpose: Accesses data by labels (row and column names). 

In [73]:
#print first row using iloc
df.iloc[0]

User_ID                         1000001
Product_ID                    P00069042
Gender                                F
Age                                0-17
Occupation                           10
City_Category                         A
Stay_In_Current_City_Years            2
Marital_Status                        0
Product_Category_1                    3
Product_Category_2                  6.0
Product_Category_3                 14.0
Purchase                           8370
Name: 0, dtype: object

In [74]:
#select last row of dataframe using iloc
df.iloc[-1]

User_ID                         1006039
Product_ID                    P00371644
Gender                                F
Age                               46-50
Occupation                            0
City_Category                         B
Stay_In_Current_City_Years           4+
Marital_Status                        1
Product_Category_1                   20
Product_Category_2                  2.0
Product_Category_3                 11.0
Purchase                            490
Name: 550067, dtype: object

In [75]:
#select first five column of data frame with all rows using iloc
df.iloc[:, 0:5]  #: for row and 0:5 for column

User_ID Product_ID Gender    Age  Occupation
0       1000001  P00069042      F   0-17          10
1       1000001  P00248942      F   0-17          10
2       1000001  P00087842      F   0-17          10
3       1000001  P00085442      F   0-17          10
4       1000002  P00285442      M    55+          16
...         ...        ...    ...    ...         ...
550063  1006033  P00372445      M  51-55          13
550064  1006035  P00375436      F  26-35           1
550065  1006036  P00375436      F  26-35          15
550066  1006038  P00375436      F    55+           1
550067  1006039  P00371644      F  46-50           0

[550068 rows x 5 columns]

In [76]:
#select first , 5th and 10th rows with 1st, 4th and 7th column using iloc

df.iloc[[0, 4, 9], [0, 3, 6]]

User_ID    Age Stay_In_Current_City_Years
0  1000001   0-17                          2
4  1000002    55+                         4+
9  1000005  26-35                          1

Task 15: Fetch row having maximum purchase amount with complete row details

Pandas provide two functions idmax() and idxmin() that return index of first occurence of maximum or minimum values over requested axis. NA/null  values are excluded from the output.
.

In [77]:
#get index of first occurences of maximum purchase value.
df1['Purchase'].idxmax()

87440

In [78]:
#get values of maximum purchase amount
df1.Purchase[df1['Purchase'].idxmax()]

23961

In [79]:
#get the row with the maximum Purchase value
df1[df1['Purchase']== 23961]

User_ID Product_ID Gender    Age  Occupation City_Category  \
87440   1001474  P00052842      M  26-35           4             A   
93016   1002272  P00052842      M  26-35           0             C   
370891  1003160  P00052842      M  26-35          17             C   

       Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
87440                           2               1                  10   
93016                           1               0                  10   
370891                          3               0                  10   

        Product_Category_2  Product_Category_3  Purchase  
87440                 15.0                 8.0     23961  
93016                 15.0                 8.0     23961  
370891                15.0                 8.0     23961

In [80]:
#get the row with the maximum Purchase value using loc
df1.loc[df1[df1['Purchase']== 23961].index]

User_ID Product_ID Gender    Age  Occupation City_Category  \
87440   1001474  P00052842      M  26-35           4             A   
93016   1002272  P00052842      M  26-35           0             C   
370891  1003160  P00052842      M  26-35          17             C   

       Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
87440                           2               1                  10   
93016                           1               0                  10   
370891                          3               0                  10   

        Product_Category_2  Product_Category_3  Purchase  
87440                 15.0                 8.0     23961  
93016                 15.0                 8.0     23961  
370891                15.0                 8.0     23961

Task 16: Get the purchase amount from 3rd row 


Pandas also provides at() and iat() functions to access a single value for a row and column pair by label or by integer position

In [81]:
#Get value at 3rd row and purchase column pair 
df1.at[2, 'Purchase']

1422

In [82]:
df1.head()

User_ID Product_ID Gender   Age  Occupation City_Category  \
0  1000001  P00069042      F  0-17          10             A   
1  1000001  P00248942      F  0-17          10             A   
2  1000001  P00087842      F  0-17          10             A   
3  1000001  P00085442      F  0-17          10             A   
4  1000002  P00285442      M   55+          16             C   

  Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
0                          2               0                   3   
1                          2               0                   1   
2                          2               0                  12   
3                          2               0                  12   
4                         4+               0                   8   

   Product_Category_2  Product_Category_3  Purchase  
0                 6.0                14.0      8370  
1                 6.0                14.0     15200  
2                 6.0                14.0      1422  
3                14.0                14.0      1057  
4                14.0                14.0      7969

In [83]:
#get value at 3rd row and 11th column pair 
df.iat[2, 11]

1422

In [84]:
df1.head()

User_ID Product_ID Gender   Age  Occupation City_Category  \
0  1000001  P00069042      F  0-17          10             A   
1  1000001  P00248942      F  0-17          10             A   
2  1000001  P00087842      F  0-17          10             A   
3  1000001  P00085442      F  0-17          10             A   
4  1000002  P00285442      M   55+          16             C   

  Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
0                          2               0                   3   
1                          2               0                   1   
2                          2               0                  12   
3                          2               0                  12   
4                         4+               0                   8   

   Product_Category_2  Product_Category_3  Purchase  
0                 6.0                14.0      8370  
1                 6.0                14.0     15200  
2                 6.0                14.0      1422  
3                14.0                14.0      1057  
4                14.0                14.0      7969

Task 16: Find the purchase amount for a user_id(1006039) and product_id(P00371644)

We can also use boolean indexing to filter and select the data :

- | for or
-  & for and
-  ~ for not

In [85]:
#get the purchase amount with a given user_id and product_id
df1.loc[((df1['User_ID'] == 1006039) & (df1['Product_ID']== 'P00371644')), 'Purchase']

550067    490
Name: Purchase, dtype: int64

In [86]:
#verify
df1.loc[550067, :]

User_ID                         1006039
Product_ID                    P00371644
Gender                                F
Age                               46-50
Occupation                            0
City_Category                         B
Stay_In_Current_City_Years           4+
Marital_Status                        1
Product_Category_1                   20
Product_Category_2                  2.0
Product_Category_3                 11.0
Purchase                            490
Name: 550067, dtype: object

Task 18: Find the user those are in City 'A' with more than 4 years and purchase amount more than 10000

In [87]:
#get the purchase amount with the given user_id and product_id
df1[(df1['City_Category'] == 'A') & (df1['Stay_In_Current_City_Years'] == '4+') & (df1['Purchase'] > 10000)]

User_ID Product_ID Gender    Age  Occupation City_Category  \
98      1000022  P00351142      M  18-25          15             A   
100     1000022  P00195942      M  18-25          15             A   
102     1000022   P0098242      M  18-25          15             A   
103     1000022  P00262242      M  18-25          15             A   
416     1000073  P00351142      M  18-25           4             A   
...         ...        ...    ...    ...         ...           ...   
545791  1006019  P00279442      M  26-35           0             A   
545792  1006019  P00262342      M  26-35           0             A   
545793  1006019  P00028842      M  26-35           0             A   
545794  1006019  P00070342      M  26-35           0             A   
545832  1006028   P0097242      M  18-25           4             A   

       Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
98                             4+               0                   1   
100                            4+               0                   3   
102                            4+               0                   1   
103                            4+               0                   1   
416                            4+               0                   1   
...                           ...             ...                 ...   
545791                         4+               0                  16   
545792                         4+               0                  15   
545793                         4+               0                   6   
545794                         4+               0                   1   
545832                         4+               0                   1   

        Product_Category_2  Product_Category_3  Purchase  
98                     8.0                17.0     12099  
100                    4.0                17.0     10681  
102                   16.0                17.0     15517  
103                   11.0                16.0     12098  
416                    8.0                17.0     15900  
...                    ...                 ...       ...  
545791                 2.0                 6.0     12453  
545792                16.0                 6.0     12667  
545793                 8.0                 6.0     16340  
545794                 2.0                14.0     15577  
545832                16.0                16.0     19682  

[6947 rows x 12 columns]

Task 19: Discard all female users are in city "B" with 3 years  and purchase amount less than 5000

In [88]:
#Get the purchase amount with the given user_id and product_id
df1[~((df1['Gender'] == 'F') & (df1['City_Category'] == 'B') & (df1['Stay_In_Current_City_Years'] == '3' & (df1['Purchase'] < 5000))]

SyntaxError: closing parenthesis ']' does not match opening parenthesis '(' (304499923.py, line 2)

In [89]:
# Get the purchase amount with the given user_id and product_id
df1[~((df1['Gender'] == 'F') & 
      (df1['City_Category'] == 'B') & 
      (df1['Stay_In_Current_City_Years'] == '3') & 
      (df1['Purchase'] < 5000))]


User_ID Product_ID Gender    Age  Occupation City_Category  \
0       1000001  P00069042      F   0-17          10             A   
1       1000001  P00248942      F   0-17          10             A   
2       1000001  P00087842      F   0-17          10             A   
3       1000001  P00085442      F   0-17          10             A   
4       1000002  P00285442      M    55+          16             C   
...         ...        ...    ...    ...         ...           ...   
550063  1006033  P00372445      M  51-55          13             B   
550064  1006035  P00375436      F  26-35           1             C   
550065  1006036  P00375436      F  26-35          15             B   
550066  1006038  P00375436      F    55+           1             C   
550067  1006039  P00371644      F  46-50           0             B   

       Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
0                               2               0                   3   
1                               2               0                   1   
2                               2               0                  12   
3                               2               0                  12   
4                              4+               0                   8   
...                           ...             ...                 ...   
550063                          1               1                  20   
550064                          3               0                  20   
550065                         4+               1                  20   
550066                          2               0                  20   
550067                         4+               1                  20   

        Product_Category_2  Product_Category_3  Purchase  
0                      6.0                14.0      8370  
1                      6.0                14.0     15200  
2                      6.0                14.0      1422  
3                     14.0                14.0      1057  
4                     14.0                14.0      7969  
...                    ...                 ...       ...  
550063                 2.0                11.0       368  
550064                 2.0                11.0       371  
550065                 2.0                11.0       137  
550066                 2.0                11.0       365  
550067                 2.0                11.0       490  

[548117 rows x 12 columns]

Task 20: Find the record in dataset with below details:
[1006038	P00375436	F	55+	1	C	2	0	20	2.0	11.0	365]

DataFrame also has an isin() method. When Calling isin(), we pass a set of values as either an array or dict. If values is an array, isin() returns a DataFrame of booleans that is the same shape as the original dataframe with True wherever the element is in the sequence of values.

In [90]:
#lets use isin() function for searching row with given values

values= [1006038,	'P00375436',	'F',	'55+',	1,	'C',	'2',	0,	20,	2.0,	11.0,	365]

df1_indexed= df1.isin(values)
df1_indexed

User_ID  Product_ID  Gender    Age  Occupation  City_Category  \
0         False       False    True  False       False          False   
1         False       False    True  False       False          False   
2         False       False    True  False       False          False   
3         False       False    True  False       False          False   
4         False       False   False   True       False           True   
...         ...         ...     ...    ...         ...            ...   
550063    False       False   False  False       False          False   
550064    False        True    True  False        True           True   
550065    False        True    True  False       False          False   
550066     True        True    True   True        True           True   
550067    False       False    True  False        True          False   

        Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
0                             True            True               False   
1                             True            True                True   
2                             True            True               False   
3                             True            True               False   
4                            False            True               False   
...                            ...             ...                 ...   
550063                       False            True                True   
550064                       False            True                True   
550065                       False            True                True   
550066                        True            True                True   
550067                       False            True                True   

        Product_Category_2  Product_Category_3  Purchase  
0                    False               False     False  
1                    False               False     False  
2                    False               False     False  
3                    False               False     False  
4                    False               False     False  
...                    ...                 ...       ...  
550063                True                True     False  
550064                True                True     False  
550065                True                True     False  
550066                True                True      True  
550067                True                True     False  

[550068 rows x 12 columns]

In [91]:
#lets use all condition

df1_indexed = df1.isin(values).all(axis= 1)   #axis=1 column wise
df1[df1_indexed]

User_ID Product_ID Gender  Age  Occupation City_Category  \
550066  1006038  P00375436      F  55+           1             C   

       Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
550066                          2               0                  20   

        Product_Category_2  Product_Category_3  Purchase  
550066                 2.0                11.0       365

We can combine DataFrames isin with the any() and all() methods to quickly select subsets of the data that meet a given criteria

Task 21: Visualize record with occupation value and mask everything left.

In [92]:
#lets use mask function with occupation value 10 

newdf= df1.mask(df['Occupation'] != 10)
newdf

User_ID Product_ID Gender   Age  Occupation City_Category  \
0       1000001.0  P00069042      F  0-17        10.0             A   
1       1000001.0  P00248942      F  0-17        10.0             A   
2       1000001.0  P00087842      F  0-17        10.0             A   
3       1000001.0  P00085442      F  0-17        10.0             A   
4             NaN        NaN    NaN   NaN         NaN           NaN   
...           ...        ...    ...   ...         ...           ...   
550063        NaN        NaN    NaN   NaN         NaN           NaN   
550064        NaN        NaN    NaN   NaN         NaN           NaN   
550065        NaN        NaN    NaN   NaN         NaN           NaN   
550066        NaN        NaN    NaN   NaN         NaN           NaN   
550067        NaN        NaN    NaN   NaN         NaN           NaN   

       Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
0                               2             0.0                 3.0   
1                               2             0.0                 1.0   
2                               2             0.0                12.0   
3                               2             0.0                12.0   
4                             NaN             NaN                 NaN   
...                           ...             ...                 ...   
550063                        NaN             NaN                 NaN   
550064                        NaN             NaN                 NaN   
550065                        NaN             NaN                 NaN   
550066                        NaN             NaN                 NaN   
550067                        NaN             NaN                 NaN   

        Product_Category_2  Product_Category_3  Purchase  
0                      6.0                14.0    8370.0  
1                      6.0                14.0   15200.0  
2                      6.0                14.0    1422.0  
3                     14.0                14.0    1057.0  
4                      NaN                 NaN       NaN  
...                    ...                 ...       ...  
550063                 NaN                 NaN       NaN  
550064                 NaN                 NaN       NaN  
550065                 NaN                 NaN       NaN  
550066                 NaN                 NaN       NaN  
550067                 NaN                 NaN       NaN  

[550068 rows x 12 columns]

Sorting in Pandas


- Sorting by label
- Sorting by actual Values

Sorting by Label
To sort a DataFrame by its index (row labels), use the sort_index() method. By default, it sorts in ascending order. To sort in descending order, set ascending=False. For sorting columns instead of rows, use axis=1.


Sorting by Values
To sort a DataFrame by the values in one or more columns, use the sort_values() method. Specify the column(s) to sort by using the by parameter.

To sort by multiple columns, pass a list to the by parameter. You can also specify different sorting orders (ascending or descending) for each column by passing a list to the ascending parameter.

Handling NaN Values
By default, sort_values() places NaN values at the end. You can change this behavior using the na_position parameter, which can be set to first or last.

Task 22: Sort Dataset with row and column wise 

Sorting By Label

We can use the sort_index() method to sort the object by labels

In [93]:
#sort dataset row wise #it is by default
df1.sort_index()

User_ID Product_ID Gender    Age  Occupation City_Category  \
0       1000001  P00069042      F   0-17          10             A   
1       1000001  P00248942      F   0-17          10             A   
2       1000001  P00087842      F   0-17          10             A   
3       1000001  P00085442      F   0-17          10             A   
4       1000002  P00285442      M    55+          16             C   
...         ...        ...    ...    ...         ...           ...   
550063  1006033  P00372445      M  51-55          13             B   
550064  1006035  P00375436      F  26-35           1             C   
550065  1006036  P00375436      F  26-35          15             B   
550066  1006038  P00375436      F    55+           1             C   
550067  1006039  P00371644      F  46-50           0             B   

       Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
0                               2               0                   3   
1                               2               0                   1   
2                               2               0                  12   
3                               2               0                  12   
4                              4+               0                   8   
...                           ...             ...                 ...   
550063                          1               1                  20   
550064                          3               0                  20   
550065                         4+               1                  20   
550066                          2               0                  20   
550067                         4+               1                  20   

        Product_Category_2  Product_Category_3  Purchase  
0                      6.0                14.0      8370  
1                      6.0                14.0     15200  
2                      6.0                14.0      1422  
3                     14.0                14.0      1057  
4                     14.0                14.0      7969  
...                    ...                 ...       ...  
550063                 2.0                11.0       368  
550064                 2.0                11.0       371  
550065                 2.0                11.0       137  
550066                 2.0                11.0       365  
550067                 2.0                11.0       490  

[550068 rows x 12 columns]

In [94]:
#sort dataset column 
df1.sort_index(axis=1)

Age City_Category Gender  Marital_Status  Occupation  \
0        0-17             A      F               0          10   
1        0-17             A      F               0          10   
2        0-17             A      F               0          10   
3        0-17             A      F               0          10   
4         55+             C      M               0          16   
...       ...           ...    ...             ...         ...   
550063  51-55             B      M               1          13   
550064  26-35             C      F               0           1   
550065  26-35             B      F               1          15   
550066    55+             C      F               0           1   
550067  46-50             B      F               1           0   

        Product_Category_1  Product_Category_2  Product_Category_3 Product_ID  \
0                        3                 6.0                14.0  P00069042   
1                        1                 6.0                14.0  P00248942   
2                       12                 6.0                14.0  P00087842   
3                       12                14.0                14.0  P00085442   
4                        8                14.0                14.0  P00285442   
...                    ...                 ...                 ...        ...   
550063                  20                 2.0                11.0  P00372445   
550064                  20                 2.0                11.0  P00375436   
550065                  20                 2.0                11.0  P00375436   
550066                  20                 2.0                11.0  P00375436   
550067                  20                 2.0                11.0  P00371644   

        Purchase Stay_In_Current_City_Years  User_ID  
0           8370                          2  1000001  
1          15200                          2  1000001  
2           1422                          2  1000001  
3           1057                          2  1000001  
4           7969                         4+  1000002  
...          ...                        ...      ...  
550063       368                          1  1006033  
550064       371                          3  1006035  
550065       137                         4+  1006036  
550066       365                          2  1006038  
550067       490                         4+  1006039  

[550068 rows x 12 columns]

The default value of axis = 0. Here sorting will be done by rows 
if we set axis = 1, sorting will be done by columns

In [95]:
#sort row wise in descending order 
df1.sort_index(ascending= False)

User_ID Product_ID Gender    Age  Occupation City_Category  \
550067  1006039  P00371644      F  46-50           0             B   
550066  1006038  P00375436      F    55+           1             C   
550065  1006036  P00375436      F  26-35          15             B   
550064  1006035  P00375436      F  26-35           1             C   
550063  1006033  P00372445      M  51-55          13             B   
...         ...        ...    ...    ...         ...           ...   
4       1000002  P00285442      M    55+          16             C   
3       1000001  P00085442      F   0-17          10             A   
2       1000001  P00087842      F   0-17          10             A   
1       1000001  P00248942      F   0-17          10             A   
0       1000001  P00069042      F   0-17          10             A   

       Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
550067                         4+               1                  20   
550066                          2               0                  20   
550065                         4+               1                  20   
550064                          3               0                  20   
550063                          1               1                  20   
...                           ...             ...                 ...   
4                              4+               0                   8   
3                               2               0                  12   
2                               2               0                  12   
1                               2               0                   1   
0                               2               0                   3   

        Product_Category_2  Product_Category_3  Purchase  
550067                 2.0                11.0       490  
550066                 2.0                11.0       365  
550065                 2.0                11.0       137  
550064                 2.0                11.0       371  
550063                 2.0                11.0       368  
...                    ...                 ...       ...  
4                     14.0                14.0      7969  
3                     14.0                14.0      1057  
2                      6.0                14.0      1422  
1                      6.0                14.0     15200  
0                      6.0                14.0      8370  

[550068 rows x 12 columns]

Sorting by Values

Task 23: Find the top 20 most revenue generated customer and their purchased product id 

Pandas provide sort_values() method to sort by values. It accepts a by argument which will use the column name of the dataframe with which the value are to be sorted .

In [96]:
#Lets try to sort dataset using purchase column
df1.sort_values(by=['Purchase'])

User_ID Product_ID Gender    Age  Occupation City_Category  \
549221  1004806  P00370293      M  26-35          17             C   
549477  1005184  P00370293      M  18-25          20             B   
547819  1002802  P00370853      M  36-45          20             B   
548027  1003105  P00370853      M  36-45          12             C   
547538  1002402  P00370853      M  46-50          17             B   
...         ...        ...    ...    ...         ...           ...   
292083  1003045  P00052842      M  46-50           1             B   
503697  1005596  P00117642      M  36-45          12             B   
370891  1003160  P00052842      M  26-35          17             C   
87440   1001474  P00052842      M  26-35           4             A   
93016   1002272  P00052842      M  26-35           0             C   

       Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
549221                          2               0                  19   
549477                         4+               1                  19   
547819                          2               0                  19   
548027                         4+               1                  19   
547538                         4+               0                  19   
...                           ...             ...                 ...   
292083                          2               1                  10   
503697                          1               0                  10   
370891                          3               0                  10   
87440                           2               1                  10   
93016                           1               0                  10   

        Product_Category_2  Product_Category_3  Purchase  
549221                 2.0                11.0        12  
549477                 2.0                11.0        12  
547819                 2.0                11.0        12  
548027                 2.0                11.0        12  
547538                 2.0                11.0        12  
...                    ...                 ...       ...  
292083                15.0                17.0     23960  
503697                16.0                 9.0     23960  
370891                15.0                 8.0     23961  
87440                 15.0                 8.0     23961  
93016                 15.0                 8.0     23961  

[550068 rows x 12 columns]

In [97]:
#sort by multiple column
df1.sort_values(by=['Age', 'Purchase']).head(10)

User_ID Product_ID Gender   Age  Occupation City_Category  \
546045  1000194  P00370853      F  0-17          10             C   
546449  1000775  P00370853      M  0-17          17             C   
550024  1005973  P00370293      M  0-17          10             C   
545971  1000086  P00370853      F  0-17          10             C   
549145  1004707  P00370293      M  0-17           0             C   
549275  1004883  P00370293      F  0-17          10             C   
546877  1001421  P00370293      F  0-17          10             A   
548545  1003865  P00370853      F  0-17          10             C   
546531  1000888  P00370853      F  0-17          10             C   
546779  1001280  P00370853      M  0-17          10             C   

       Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
546045                          3               0                  19   
546449                          1               0                  19   
550024                         4+               0                  19   
545971                          3               0                  19   
549145                         4+               0                  19   
549275                          1               0                  19   
546877                          1               0                  19   
548545                          2               0                  19   
546531                          1               0                  19   
546779                          1               0                  19   

        Product_Category_2  Product_Category_3  Purchase  
546045                 2.0                11.0        12  
546449                 2.0                11.0        12  
550024                 2.0                11.0        12  
545971                 2.0                11.0        13  
549145                 2.0                11.0        13  
549275                 2.0                11.0        13  
546877                 2.0                11.0        14  
548545                 2.0                11.0        14  
546531                 2.0                11.0        24  
546779                 2.0                11.0        24

In [98]:
#sort in descending order
df1.sort_values(by='Purchase', ascending = False)

User_ID Product_ID Gender    Age  Occupation City_Category  \
370891  1003160  P00052842      M  26-35          17             C   
93016   1002272  P00052842      M  26-35           0             C   
87440   1001474  P00052842      M  26-35           4             A   
503697  1005596  P00117642      M  36-45          12             B   
321782  1001577  P00052842      M    55+           0             C   
...         ...        ...    ...    ...         ...           ...   
546379  1000671  P00370853      M  18-25           4             C   
546185  1000391  P00370293      M  46-50          11             C   
547032  1001649  P00370293      M  18-25          19             C   
546181  1000387  P00370293      F  36-45           7             C   
549221  1004806  P00370293      M  26-35          17             C   

       Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
370891                          3               0                  10   
93016                           1               0                  10   
87440                           2               1                  10   
503697                          1               0                  10   
321782                          1               1                  10   
...                           ...             ...                 ...   
546379                          0               0                  19   
546185                          2               1                  19   
547032                          2               1                  19   
546181                          0               0                  19   
549221                          2               0                  19   

        Product_Category_2  Product_Category_3  Purchase  
370891                15.0                 8.0     23961  
93016                 15.0                 8.0     23961  
87440                 15.0                 8.0     23961  
503697                16.0                 9.0     23960  
321782                15.0                17.0     23960  
...                    ...                 ...       ...  
546379                 2.0                11.0        12  
546185                 2.0                11.0        12  
547032                 2.0                11.0        12  
546181                 2.0                11.0        12  
549221                 2.0                11.0        12  

[550068 rows x 12 columns]

In [99]:
#lets get the top 20 (row= [:20])  using iloc for Purchase
top20= df1.sort_values(by=['Purchase'], ascending= False).iloc[:20, :]
top20

User_ID Product_ID Gender    Age  Occupation City_Category  \
370891  1003160  P00052842      M  26-35          17             C   
93016   1002272  P00052842      M  26-35           0             C   
87440   1001474  P00052842      M  26-35           4             A   
503697  1005596  P00117642      M  36-45          12             B   
321782  1001577  P00052842      M    55+           0             C   
349658  1005848  P00119342      M  51-55          20             A   
292083  1003045  P00052842      M  46-50           1             B   
298378  1003947  P00116142      M  26-35           0             C   
437804  1001387  P00086242      F  51-55          13             B   
229329  1005367  P00085342      M  18-25           4             A   
416883  1004117  P00161842      M  18-25           4             B   
7542    1001178  P00116142      M    55+           0             C   
373300  1003511  P00085342      M  51-55           0             C   
33268   1005102  P00052842      M  26-35          12             C   
388010  1005716  P00052842      M   0-17          10             C   
449656  1003301  P00086242      F  26-35           2             B   
366333  1002359  P00085342      M    55+          13             C   
54364   1002274  P00052842      M  18-25           2             B   
56879   1002788  P00085342      M    55+           1             B   
68926   1004520  P00116142      M  26-35           4             C   

       Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
370891                          3               0                  10   
93016                           1               0                  10   
87440                           2               1                  10   
503697                          1               0                  10   
321782                          1               1                  10   
349658                          0               1                  10   
292083                          2               1                  10   
298378                          3               0                  10   
437804                          1               1                  10   
229329                          1               0                  10   
416883                         4+               0                  10   
7542                            1               1                  10   
373300                          2               1                  10   
33268                           2               0                  10   
388010                         4+               0                  10   
449656                          3               0                  10   
366333                          1               1                  10   
54364                           3               0                  10   
56879                           0               1                  10   
68926                           1               1                  10   

        Product_Category_2  Product_Category_3  Purchase  
370891                15.0                 8.0     23961  
93016                 15.0                 8.0     23961  
87440                 15.0                 8.0     23961  
503697                16.0                 9.0     23960  
321782                15.0                17.0     23960  
349658                13.0                 5.0     23960  
292083                15.0                17.0     23960  
298378                13.0                16.0     23959  
437804                14.0                 5.0     23959  
229329                13.0                16.0     23958  
416883                13.0                16.0     23958  
7542                  13.0                16.0     23958  
373300                13.0                15.0     23958  
33268                 15.0                 8.0     23956  
388010                15.0                 4.0     23955  
449656                 6.0                13.0     23955  


In [100]:
#get list of top 20 user id
top20.User_ID.values

array([1003160, 1002272, 1001474, 1005596, 1001577, 1005848, 1003045,
       1003947, 1001387, 1005367, 1004117, 1001178, 1003511, 1005102,
       1005716, 1003301, 1002359, 1002274, 1002788, 1004520], dtype=int64)

In [101]:
# visualize products included in top 20
top20.Product_ID.value_counts()

Product_ID
P00052842    8
P00085342    4
P00116142    3
P00086242    2
P00117642    1
P00119342    1
P00161842    1
Name: count, dtype: int64

Task 24: Find which age group is much active for purchasing product from website

Exploring Categorical Data

In [102]:
#lets use unique to get distinct values
df1['Gender'].unique()

array(['F', 'M'], dtype=object)

In [103]:
#lets use value_counts to  get count of distinct values

df1['Gender'].value_counts()

Gender
M    414259
F    135809
Name: count, dtype: int64

In [104]:
#sort with respect to count
df1['Gender'].value_counts(ascending= True)

Gender
F    135809
M    414259
Name: count, dtype: int64

In [105]:
#lets get age count sorted in descending order
df1['Age'].value_counts(ascending = False)

Age
26-35    219587
36-45    110013
18-25     99660
46-50     45701
51-55     38501
55+       21504
0-17      15102
Name: count, dtype: int64

In [106]:
#we can also replace for column values
df1['Gender']=df1['Gender'].replace('F', 'Female')
df1['Gender']=df1['Gender'].replace('M', 'Male')

In [107]:
#verify
df1.head()

User_ID Product_ID  Gender   Age  Occupation City_Category  \
0  1000001  P00069042  Female  0-17          10             A   
1  1000001  P00248942  Female  0-17          10             A   
2  1000001  P00087842  Female  0-17          10             A   
3  1000001  P00085442  Female  0-17          10             A   
4  1000002  P00285442    Male   55+          16             C   

  Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
0                          2               0                   3   
1                          2               0                   1   
2                          2               0                  12   
3                          2               0                  12   
4                         4+               0                   8   

   Product_Category_2  Product_Category_3  Purchase  
0                 6.0                14.0      8370  
1                 6.0                14.0     15200  
2                 6.0                14.0      1422  
3                14.0                14.0      1057  
4                14.0                14.0      7969

Task 25: Generate the list of user_id with corresponding age and find the total count of purchases that have done

In [108]:
#lets get list first using values of 'tolist'
df1[['User_ID', 'Age']].values.tolist()

[[1000001, '0-17'],
 [1000001, '0-17'],
 [1000001, '0-17'],
 [1000001, '0-17'],
 [1000002, '55+'],
 [1000003, '26-35'],
 [1000004, '46-50'],
 [1000004, '46-50'],
 [1000004, '46-50'],
 [1000005, '26-35'],
 [1000005, '26-35'],
 [1000005, '26-35'],
 [1000005, '26-35'],
 [1000005, '26-35'],
 [1000006, '51-55'],
 [1000006, '51-55'],
 [1000006, '51-55'],
 [1000006, '51-55'],
 [1000007, '36-45'],
 [1000008, '26-35'],
 [1000008, '26-35'],
 [1000008, '26-35'],
 [1000008, '26-35'],
 [1000008, '26-35'],
 [1000008, '26-35'],
 [1000009, '26-35'],
 [1000009, '26-35'],
 [1000009, '26-35'],
 [1000009, '26-35'],
 [1000010, '36-45'],
 [1000010, '36-45'],
 [1000010, '36-45'],
 [1000010, '36-45'],
 [1000010, '36-45'],
 [1000010, '36-45'],
 [1000010, '36-45'],
 [1000010, '36-45'],
 [1000010, '36-45'],
 [1000010, '36-45'],
 [1000010, '36-45'],
 [1000010, '36-45'],
 [1000010, '36-45'],
 [1000010, '36-45'],
 [1000010, '36-45'],
 [1000010, '36-45'],
 [1000010, '36-45'],
 [1000010, '36-45'],
 [1000011, '26-35']

In the result you see user id 10000001 has age group 0-17 and repeated 3 times. means 0-17 age group has purchesed item  multiple times , but we want count of purchases and that count should be unique..

In [109]:
#lets check for count purchases for all distinct user_id and age combination
df1[['User_ID', 'Age']].value_counts()

User_ID  Age  
1001680  26-35    1026
1004277  36-45     979
1001941  36-45     898
1001181  36-45     862
1000889  46-50     823
                  ... 
1002111  55+         7
1005391  26-35       7
1002690  26-35       7
1005608  18-25       7
1000708  26-35       6
Name: count, Length: 5891, dtype: int64

Task 26: Get the different statistical values for Purchase column

Aggregations in Pandas: there are several method for this

In [110]:
#import numpy
import numpy as np

In [111]:
#Lets use describe on Purchase
df1['Purchase'].describe()

count    550068.000000
mean       9263.968713
std        5023.065394
min          12.000000
25%        5823.000000
50%        8047.000000
75%       12054.000000
max       23961.000000
Name: Purchase, dtype: float64

Task 27: Find the total amount generated via website by selling product

we can apply aggregation on a single column of a dataframe

In [112]:
#lets use np.sum aggregation to get total purchasesd amount
df1['Purchase'].aggregate(np.sum)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_2008\2610252904.py:2: FutureWarning: The provided callable <function sum at 0x000002151FBC4A40> is currently using Series.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df1['Purchase'].aggregate(np.sum)


5095812742

we can also apply multiple fiunctions on a single column of dataframe

In [113]:
#Find sum and mean value after doing aggregation over purchase column
df1['Purchase'].aggregate([np.sum, np.mean])

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_2008\2228951556.py:2: FutureWarning: The provided callable <function sum at 0x000002151FBC4A40> is currently using Series.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df1['Purchase'].aggregate([np.sum, np.mean])
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_2008\2228951556.py:2: FutureWarning: The provided callable <function mean at 0x000002151FBC5B20> is currently using Series.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  df1['Purchase'].aggregate([np.sum, np.mean])


sum     5.095813e+09
mean    9.263969e+03
Name: Purchase, dtype: float64

We can also apply aggregation on multiple columns of a dataframe 

In [114]:
#find mean for 'Product_Category_1', 'Product_Category_2', 'Product_Category_3'
df1[['Product_Category_1', 'Product_Category_2', 'Product_Category_3']].aggregate(np.mean)


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_2008\4206337797.py:2: FutureWarning: The provided callable <function mean at 0x000002151FBC5B20> is currently using DataFrame.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  df1[['Product_Category_1', 'Product_Category_2', 'Product_Category_3']].aggregate(np.mean)


Product_Category_1     5.404270
Product_Category_2     9.863190
Product_Category_3    12.650723
dtype: float64

We can also apply multiple functions on multiple columns of a dataframe

In [115]:
##find mean and sum for 'Product_Category_1', 'Product_Category_2', 'Product_Category_3'
df1[['Product_Category_1', 'Product_Category_2', 'Product_Category_3']].aggregate([np.sum, np.mean])

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_2008\2144756459.py:2: FutureWarning: The provided callable <function sum at 0x000002151FBC4A40> is currently using Series.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df1[['Product_Category_1', 'Product_Category_2', 'Product_Category_3']].aggregate([np.sum, np.mean])
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_2008\2144756459.py:2: FutureWarning: The provided callable <function mean at 0x000002151FBC5B20> is currently using Series.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  df1[['Product_Category_1', 'Product_Category_2', 'Product_Category_3']].aggregate([np.sum, np.mean])


Product_Category_1  Product_Category_2  Product_Category_3
sum         2.972716e+06        5.425425e+06        6.958758e+06
mean        5.404270e+00        9.863190e+00        1.265072e+01

Task 28: Tag records to 'high focused' transection where purchase amount has been more than 5000. Remaining can be tagged as general transection

Functions application in pandas

Row and Column wise function application apply()

In [116]:
#Try to use apply function on product_category_1
df1.Product_Category_1.apply(lambda x : x*10)

0          30
1          10
2         120
3         120
4          80
         ... 
550063    200
550064    200
550065    200
550066    200
550067    200
Name: Product_Category_1, Length: 550068, dtype: int64

In [117]:
df1.head()

User_ID Product_ID  Gender   Age  Occupation City_Category  \
0  1000001  P00069042  Female  0-17          10             A   
1  1000001  P00248942  Female  0-17          10             A   
2  1000001  P00087842  Female  0-17          10             A   
3  1000001  P00085442  Female  0-17          10             A   
4  1000002  P00285442    Male   55+          16             C   

  Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
0                          2               0                   3   
1                          2               0                   1   
2                          2               0                  12   
3                          2               0                  12   
4                         4+               0                   8   

   Product_Category_2  Product_Category_3  Purchase  
0                 6.0                14.0      8370  
1                 6.0                14.0     15200  
2                 6.0                14.0      1422  
3                14.0                14.0      1057  
4                14.0                14.0      7969

lambda function: Lambda functions in Python are powerful, concise tools for creating small, anonymous functions on the fly. 
They are perfect for simplifying short-term tasks, streamlining code with higher-order functions like map , filter , or sorted , 
and reducing clutter when defining temporary or throwaway logic.

In [118]:
#lets add new column as 'category' which will have tags based on purchase amount


In [119]:
#lets check value for high forward row #x = 'Purchase' if x > 5000 (highly focused) and if x < 5000 (general)
df1['Category']= df1.Purchase.apply(lambda x: 'High Focused' if x > 5000 else 'General')
df1.head()

User_ID Product_ID  Gender   Age  Occupation City_Category  \
0  1000001  P00069042  Female  0-17          10             A   
1  1000001  P00248942  Female  0-17          10             A   
2  1000001  P00087842  Female  0-17          10             A   
3  1000001  P00085442  Female  0-17          10             A   
4  1000002  P00285442    Male   55+          16             C   

  Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
0                          2               0                   3   
1                          2               0                   1   
2                          2               0                  12   
3                          2               0                  12   
4                         4+               0                   8   

   Product_Category_2  Product_Category_3  Purchase      Category  
0                 6.0                14.0      8370  High Focused  
1                 6.0                14.0     15200  High Focused  
2                 6.0                14.0      1422       General  
3                14.0                14.0      1057       General  
4                14.0                14.0      7969  High Focused

In [120]:
#Lets check value_counts for high focused row
df1.Category.value_counts()

Category
High Focused    455145
General          94923
Name: count, dtype: int64

Task 29: Based on gender check the total purchased amount and average purchasing amount

Pandas GroupBy operation

In [ ]:
#Use groupBy on top of gender column
df1.groupby('Gender')

In [122]:
#See the groups
df1.groupby('Gender').groups

{'Female': [0, 1, 2, 3, 14, 15, 16, 17, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 65, 66, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 124, 125, 126, 147, 148, 149, 150, 151, 156, 157, 158, 163, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 219, 222, 223, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 297, 298, 299, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 373, ...], 'Male': [4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 67, 68, 69, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 152, 153, ...]}

Group by with multiple columns

In [123]:
#get groups based on gender and age combination
df1.groupby(['Gender', 'Age']).groups

{('Female', '0-17'): [0, 1, 2, 3, 299, 423, 424, 425, 426, 427, 428, 429, 430, 431, 432, 467, 468, 539, 540, 541, 542, 543, 617, 618, 619, 620, 621, 1150, 1151, 1304, 1305, 1306, 2905, 2907, 3010, 3715, 3804, 3805, 3806, 3807, 3808, 3835, 3836, 4551, 4552, 4553, 4554, 4555, 5453, 6431, 6759, 6760, 6761, 6762, 6763, 6764, 6765, 6766, 6767, 6768, 6769, 6770, 6771, 6772, 6773, 6774, 6775, 6776, 6777, 6778, 6779, 6780, 6781, 6782, 6783, 6784, 6785, 6786, 6787, 6788, 6789, 6790, 6791, 6792, 6793, 6794, 6795, 6796, 6797, 6798, 6799, 6800, 6801, 6802, 6803, 6804, 6805, 6806, 6807, 6808, ...], ('Female', '18-25'): [70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 222, 223, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 547, 548, 549, 550, 625, 910, 911, 912, 913, 914, 1046, 1228, 1267, 1268, 1269, 1490, 1491, 1492, 1493, 1494, 1495, 1496, 1497, 1498, 1499, 1500, 1552, 1553, 1554, 1555, 1556, 1665, 1666, 16

In [ ]:
#Apply aggregation function (in gender) sum with groupby
df1.groupby('Gender').sum()

In [ ]:
#use np.sum

df1.groupby('Gender').agg(np.sum)

In [ ]:
#get total purchased amount
df1.groupby('Gender')['Purchase'].agg(np.sum)

In [ ]:
#get sum as well as mean
df1.groupby('Gender')['Purchase'].agg([np.sum, np.mean])

#from output we can say that male are purchasing the more goods than female

In [ ]:
#we can also apply function on top of groups
df1[df1.groupby('Gender')['Purchase'].apply(lambda x: x> 10000)]

In [ ]:
df1.head()

Task 30: Create new columns based on city_category values and drop the original coloumn

Handling multi-valued categorical column

In [ ]:
#check different value for city_category
df1.City_Category.value_counts()

In [ ]:
#apply get_dummies function to get new columns
dummy_df= pd.get_dummies(df1.City_Category, drop_first= True)

In [ ]:
dummy_df.head()

In [ ]:
#concatenate both dataframes
df1.pd.concat([df1,dummy_df],axis= 1)

In [ ]:
#verify
df1

In [ ]:
#drop original one
df1.drop(['City_Category'], axis=1, inplace=True)

In [ ]:
#verify
df1.head()
#as output you got no any column with city category

In [ ]:
#also verify shape
df1.shape  #tell number of rows and column

#output= (550068, 14)  #coumn = 12-1+3 = 14 (3 column extra added and 1 column dropped)

So with this , it can be said that we already have explored a lot and we can go ahead with visual exploration and model building 

Glimps of important activities we did using Pandas

-Generated descriptive statistics value for numerical columns. Also explored categorical columns.
-Got percentage distributed of each product id available in dataset and found with highest occuring product id in dataset .
-Handled missing values using dropping and imputing both options
-Fetch maximum purchase amount with complete row details
-Found the purchase amount for a specified user_id and product_id
-Found some interesting subset of dataset based on given conditions.
-Found top 20 most relevant generated customers and their purchased product_id
-Found which age group is much active for purchasing product from website
-Found the total amount generated via website by selling product
-Tagged records to "High Focused" transections where purchased amount has been more tha 5000
-Based on gender, got the total purchased amount and average purchasing amount